### PR TITLE
16 set get and clear excel document properties

### PR DESCRIPTION
**Pull request by stuart-kiandra**
Add actions to set, get and clear Excel document properties.
I have found this useful in removing personal identifiable information (PII) from downloaded Excel documents produced from templates supplied by the customer. By clearing excel document properties, we resolved a related security testing issue raised during penetration testing.

### CODE REVIEW

**Comment by stuart-kiandra** [comment]
Hanno, if you're happy with this, I can release an updated version of the library. Otherwise, if you prefer, I can wait for it to be included in a later release. We are running with (a subset of) this code in a modified version of the library for one of our clients.

**Comment by stuart-kiandra** [comment]
Hi Hanno,
Yes that would be much better. The reason for the different naming is there is already a Workbook_GetProperties that gets information about worksheets that is useful, but not related to what Excel calls properties. I wanted to respect what has already been done.
Do you think it would be better to rename the existing Workbook_GetProperties and Worksheet_GetProperties; maybe GetInfo and maybe Workbook_GetWorksheets?

**Comment by HannoCoetzee** [comment]
I agree `Workbook_GetProperties` is used in the wrong context and should be used for the actual properties you are now working with.

Proposed change:
Refactor `Workbook_GetProperties` for what you need and move the existing to code in that function to a new function called `Worksheet_GetPropertiesAll`?

**Comment by stuart-kiandra** [comment]
Ok will do, thanks for your input and review!

**Review by HannoCoetzee — APPROVED** [review]
Thank you, @stuart-kiandra. Looks good.

**Pull request merged**
