### PR TITLE
Added convert hex code to RGB and get fill color by name and index

### PR DESCRIPTION
**Pull request by beatriz-sabino**
I created these functions:

- Cell_ConvertHexCodeToRGB
- Cell_GetFillColorByIndex
- Cell_GetFillColorByName

The last two functions were previously requested https://www.outsystems.com/forums/discussion/81003/advanced-excel-check-cell-background-color-of-imported-excel/

### CODE REVIEW

**Comment by beatriz-sabino** [comment]
Hi @HannoCoetzee! Is there a possibility to review and add this code? Thank you!

**Comment by HannoCoetzee** [comment]
@beatriz-sabino would you mind adding your updated .xif file to the PR, please?
It saves me a lot of time because I don't have to manually add the actions with descriptions, etc.
Also, if the code works well, you can update the component on the Forge even before the PR is approved because you are part of the team.

**Comment by HannoCoetzee** [comment]
Did you get the latest code before submitting the PR because I see some conflicts relating to the Get/Set_Properties?

**Comment by beatriz-sabino** [comment]
Hi @HannoCoetzee!  Yes, I believe I did pull the latest code, but considering this PR is nearly a year old, I can't quite recall all the details.
Here is the .xif file from when I added the code.
[Advanced_Excel_v37.zip](https://github.com/user-attachments/files/18036286/Advanced_Excel_v37.zip)

**Comment by HannoCoetzee** [comment]
Changes implemented with this commit: https://github.com/HannoCoetzee/outsystems_advancedexcel/commit/a9b8e0188c00e8e5fb6b7c8b24e37632221cbe8f

Thank you, @beatriz-sabino

**Pull request closed without merging**
